### ISSUE TITLE
ESLint Library Config Error

### ISSUE THREAD

**Issue by AriZargaran** [inspiratweb/Diet#18] opened 2020-05-11 11:46 UTC
<img width="119" alt="Screenshot 2020-05-11 at 13 41 11" src="https://user-images.githubusercontent.com/56269617/81558302-bdab1880-938d-11ea-9ba1-e911535b233e.png">

Failing to load the ESLint library for our repo docs

> Error Log:
``` 
To use ESLint please install eslint by running npm install eslint in the workspace folder newDiet
or globally using 'npm install -g eslint'. You need to reopen the workspace after installing eslint.

If you are using yarn or pnpm instead of npm set the setting `eslint.packageManager` to either `yarn` or `pnpm`
Alternatively you can disable ESLint for the workspace folder xxx by executing the 'Disable ESLint' command.

- ESLint library loaded from: /node_modules/eslint/lib/api.js
- [Error] node_modules/eslint-config-airbnb/index.js Error: ENOENT: no such file or directory, open 'node_modules/eslint-config-airbnb/index.js' Referenced from: .eslintrc

**Comment by ArianZargaran** [comment] 2020-05-13 12:11
DONE! Closing per the issue is fixed

**Closed by ArianZargaran** 2020-05-13 12:11 UTC
Labels: config update
